spring:
  datasource:
    url: "jdbc:sqlserver://localhost:1433;databaseName=UnipuResults;encrypt=false;"
    username: rpuser
    password: 1234
    driverClassName: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
  jpa:
    show-sql: false
    hibernate:
      dialect: org.hibernate.dialect.SQLServerDialect
      naming:
        # Spring by default uses org.springframework.boot.orm.jpa.SpringNamingStrategy
        #which splits camel case names with underscore. I DON'T WANT THAT
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  main:
    web-environment: true
  liquibase:
    change-log: classpath:db.changelog/db.changelog-production.yaml



